### ISSUE TITLE
new node.can_tag(tagname, user) check in DrupalNode model

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#1034]
## Problem

Both co-authorship (#761) and wiki locking (#397) features need a check in `node.add_tag(tagname, user)` to determine if the given user is allowed to make that kind of power tag -- now that we have some more powerful "power tags" -- https://publiclab.org/wiki/power-tags and both locking and co-authorship permissions will be tag-based. 

## Solution

I propose a new method called `node.can_tag(tagname, user)` which compares the tagname and determines if this user is allowed to apply that tag to this node. It'd go here:

https://github.com/publiclab/plots2/blob/master/app/models/drupal_node.rb

and can be based on the comparisons currently done in the tag_controller:

https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L114-L121

Once we create this **and unit-test it**, both co-authorship and wiki locking can use it -- and we can even add it to `node.add_tag()` and unit-test it. 

Also, controllers will be able to check for this and produce helpful error messages, more compactly than is done in the tag controller now:

https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L114-L121

This is also helpful because right now, tags can be added outside that controller (like on this line: https://github.com/publiclab/plots2/blob/master/app/controllers/notes_controller.rb#L141-L144) which bypass the tag_controller filters. 

So let's begin with just the `can_tag()` method and then break out the next steps!

**Comment by ashleypt** [comment]
@ashleypt @jywarren okay working on this one now :)

**Comment by ashleypt** [comment]
fixed https://github.com/publiclab/plots2/pull/1058

**Comment by jywarren** [comment]
OK - that caused some havoc -- #1062 - but can_tag now exists -- some of the unit tests are still not working properly. But next steps are:

* finish unit test debugging
* adapt this to use the new `can_tag` method: https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L114-L121
* add to list of permissions with co-authorship (#761) and wiki locking (#397) powertags

**Comment by jywarren** [comment]
This is now complete in #1095! Thanks!!!
