### ISSUE TITLE
Convert files in /app/views/spam2/ directory to 2-space indentation

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#10952]
This is a small change, but we have a standard across almost all our projects for double-space indentation, that is, each indent level is made with 2 spaces, not tabs. But a few files use tabs - we could make an FTO to convert each one, maybe?

https://github.com/publiclab/plots2/tree/main/app/views/spam2/ <- a lot of these files have tab indents. Let's make them into double-space indented files!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by stephaniequintana** [comment]
As mentioned, there are several files in this directory, namely
* _comments.html.erb
* _flags.html.erb
* _insights.html.erb
* _nodes.html.erb
* _queue.html.erb
* _revisions.html.erb
* spam.html.erb and
* _users.html.erb

Please choose one file at a time to work on so that others may contribute to and learn the process. Please leave a comment identifying the file you are working on so that others do not choose it as well.

**Comment by stephaniequintana** [comment]
I will begin with the _comments.html.erb file.
Please let me know if you have already begun working with this file.

**Comment by jywarren** [comment]
Hi @stephaniequintana @akanbifatimah just be aware that "_nodes.html" is being edited in this PR: (https://github.com/publiclab/plots2/pull/10913) and due to the nature of the changes (affecting each line) it could introduce a git conflict to work on that at the same time. So best choose another file!

Thanks all!

**Comment by akanbifatimah** [comment]
I will begin with _flags.html.erb file.

**Comment by akanbifatimah** [comment]
> Hi @stephaniequintana @akanbifatimah just be aware that "_nodes.html" is being edited in this PR: (#10913) and due to the nature of the changes (affecting each line) it could introduce a git conflict to work on that at the same time. So best choose another file!
> 
> Thanks all!

well noted @jywarren ,thank you.

**Comment by PeculiarE** [comment]
I'd check out the _spam.html.erb file 😄. Thank you

**Comment by VictoriaAjala** [comment]
Hi!, I will work on the _users.html.erb file. Thank you!

**Comment by on2onyekachi** [comment]
@stephaniequintana I'll be working on [flags.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/spam2/_flags.html.erb)

**Comment by kunmi02** [comment]
Hi, I will work on the [revisions.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/spam2/_revisions.html.erb)

**Comment by TildaDares** [comment]
Just noting that #10969 has been merged so you're free to work on `nodes.html.erb`.

**Comment by TildaDares** [comment]
Thanks for working on this everyone. Just noting that the only files that should be corrected are the ones with JavaScript. We don't have to indent the HTML so that we don't have too many changes. Thanks!!

**Comment by Somya-Singhal** [comment]
@TildaDares @stephaniequintana I would like to start working with [queue.html.erb](queue.html.erb).

**Comment by VictoriaAjala** [comment]
Hi @TildaDares, It seems like the users.html.erb issue has already been resolved, I'd like to work on nodes.html.erb

**Comment by TildaDares** [comment]
Hi @VictoriaAjala, go ahead. Thanks!

**Comment by VictoriaAjala** [comment]
Hello @TildaDares, I have gone through the file and I can't find the tab issues, It seems it has been fixed.

**Comment by Somya-Singhal** [comment]
I think @VictoriaAjala , you are confused that we had to work on this issue. But instead we had to make an FTO issue for the chosen file, like you choosed to work upon [nodes.html.erb](nodes.html.erb), so you have to go through that file and create an FTO issue by specifying a small change, that is making double-space indentation(each indent level is made with 2 spaces) not tabs as told by @jywarren above.
I think this could help you!!😅

**Comment by TildaDares** [comment]
@VictoriaAjala The problem is still there. I can still see it.

**Comment by VictoriaAjala** [comment]
Oh Thanks! @Somya-Singhal . I can see it now @TildaDares . Thank you!

**Comment by TildaDares** [comment]
All done. Thanks everyone!!
