### ISSUE TITLE
Bug in URLs that have an `at` symbol (`@`)

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2423]
### Please describe the problem

I pasted in a link to an external site in my research note: https://medium.com/@sunnydeveloper/new-diversity-inclusion-in-open-source-community-call-52d01324e0a9

It seems like the ampersand "`@`" may have broken the rest of the link after the following slash. Maybe it is being read as a publiclab.org username? 

> What did you expect to see that you didn't?

I expected to see the link work without needing additional markdown. I attempted to use both markdown and html to better contain the link, but that ampersand breaks it every time. 

### Please show us where to look

https://publiclab.org/notes/liz/02-28-2018/convening-diversity-and-inclusion-initiatives-across-open-source-projects

**Comment by ebarry** [comment]
@icarito , i just spotted this old issue, and am wondering if you might know if perhaps we have fixed this already?

**Comment by icarito** [comment]
Frankly I have no idea I guess the only way to know is to try. It's strange that this issue seems to have slipped by, looks like the logic that makes the `@mention` links doesn't detect when it's part of a URL.

**Comment by icarito** [comment]
I just did the testing and indeed this issue is not fixed. It's not the `amperstand` (`&`), but the `at` symbol (`@`) that triggers the problem.

**Comment by icarito** [comment]
https://publiclab.org/notes/liz/02-28-2018/convening-diversity-and-inclusion-initiatives-across-open-source-projects#c26931 I tested it in a comment

**Comment by ebarry** [comment]
Thank you @icarito !

**Comment by icarito** [comment]
Hi @ebarry - it struck me that there's a simple workaround for this to work in this case.

Characters in URLs can be escaped, by using the % symbol.
The symbol for `at` `@`, is %40.

So the URL becomes https://medium.com/%40sunnydeveloper/new-diversity-inclusion-in-open-source-community-call-52d01324e0a9 and this link doesn't suffer from the `@mention` link.

Hope it helps!

**Comment by icarito** [comment]
I tried it and confirmed at https://publiclab.org/notes/liz/02-28-2018/convening-diversity-and-inclusion-initiatives-across-open-source-projects#c26952

**Comment by jywarren** [comment]
All good now!
