### ISSUE TITLE
Remove background from wiki links shown on profile sidebar 

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#4980]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: 
On /profile/[username] in the sidebar, links display colored background on hover, let's remove the background color from the links

![Screenshot from 2019-03-10 03-14-29](https://user-images.githubusercontent.com/20878070/54077779-5904b180-42e3-11e9-8c14-28742dff5af6.png)

Update this line of code 
https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb#L284
so that on hovering over the links, no color is shown.

Also, try to shift the icon in the colored zone and upload the screenshot asking which view is looking better?

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by gauravano** [comment]
This issue is created for @EngrEric. Thanks!

**Comment by EngrEric** [comment]
Thanks

**Comment by EngrEric** [comment]
@gauravano, I am trying to setup the project locally on my computer but has this error
`Gem::LoadError: mysql2 is not part of the bundle. Add it to your Gemfile.`

**Comment by gauravano** [comment]
Hi @EngrEric, we are working on solving this issue. You can try some temporary fixes given here - https://github.com/publiclab/plots2/issues/4936 in the meantime. Sorry for the inconvenience.

**Comment by EngrEric** [comment]
@gauravano see what i have
![image](https://user-images.githubusercontent.com/34476840/54275101-17e1fb00-458a-11e9-83e4-4deb04ebc819.png)
![image](https://user-images.githubusercontent.com/34476840/54275202-5081d480-458a-11e9-82e5-d436d8727831.png)

**Comment by EngrEric** [comment]
@gauravano  please is there a slack channel here

**Comment by luanafaustini** [comment]
Hello,I would like to help with this or any other issue. 
@EngrEric can I help you with something? I'm new at HTML and CSS, but I'm sure can try my best.

@gauravano Would you like to create an issue for me?

Thank you!

**Comment by gauravano** [comment]
Hi @EngrEric, please update your fork as this issue is recently resolved. 

@luanafaustini you can start working on https://github.com/publiclab/plots2/issues/5051. Thanks!

**Comment by EngrEric** [comment]
@gauravano  is there another issue i should work on?

**Comment by gauravano** [comment]
have you raised fix for this issue? @EngrEric

**Comment by EngrEric** [comment]
@gauravano, no.
What are the steps to raise the fix.
To open a pull request?
Again, I am still having mysql2 issue...

**Comment by gauravano** [comment]
Rebase your local branch with master as fix for the issue is already merged

**Comment by EngrEric** [comment]
@gauravano Do I still have to present it as my contribution at outreachy or you will create another one for me.

**Comment by gauravano** [comment]
You have to solve this or another issue and submit it at outreachy portal

**Comment by EngrEric** [comment]
Cool, in want to solve this one.
@gauravano thanks for your help so far.
My greatest challenge is to get this run on my local machine.
The fix will not be hard for me.
At least am about 6 months older developer world.

**Comment by gauravano** [comment]
Great! Give it a try and if you get stuck on updating PR branch then let me know. Thanks!

**Comment by EngrEric** [comment]
@gauravano i have fixed this issue.
this is my solution. 
please take a look at it

**Comment by Priyak5** [comment]
Hello! I would like to work on this if not solved or any other first timer issue. I have experience in HTML and CSS through school projects and will try my best. 
@gauravano  is there any issue I can work on?
Any help is appreciated!
Thank you!

**Comment by gauravano** [comment]
Hi @Priyak5, I have added your name to https://github.com/publiclab/plots2/issues/4963#issue-418960660 and will ping you soon with a new/appropriate issue. Thanks!

**Comment by vaarigupta** [comment]
hello @gauravano    I am an outreachy applicant and excited  to work on this issue. How can I start contributing ?

**Comment by gauravano** [comment]
Hey @vaarigupta, you can start working on this https://github.com/publiclab/plots2/issues/5191 . Thanks!

**Comment by vaarigupta** [comment]
I

> Hey @vaarigupta, you can start working on this #5191 . Thanks!

Ya sure I look into it 
Thanks @gauravano

**Comment by EngrEric** [comment]
@gauravano 
please i think you are my mentor here.
your attention is needed here.
```Please work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step. Make sure take into account any time commitments you have during the Outreachy internship round. If you are still working on your contributions and need more time, you can leave this blank and edit your application later.```

**Comment by EngrEric** [comment]
@gauravano .
THIS IS THE TASK I WANT TO WORK ON DURING THE INTERNSHIP
```Modifying the People page to show a map on the right side```
how do make a timeline for it as wanted by outreachy

**Comment by gauravano** [comment]
Hi @EngrEric, you have to make a timeline where you'll be mentioning which tasks(from https://github.com/publiclab/plots2/issues/4922) you'll be doing in each week. Also, dedicate some time to testing with each week if you think that week's task requires it. Or, you can plan for tests at end (if testing is required)

Start making a timeline in your proposal and I or some other mentor will review and suggest the changes. Thanks!

**Comment by Linda-Ikechukwu** [comment]
Hi, this issue is still open, can I take it up? I'm an outreachy intern applicant

**Comment by khadija-nur** [comment]
@avats-dev Thank you for assigning me 👍

**Comment by khadija-nur** [comment]
Hi @avats-dev it seems like this issue has already been resolved 
- The link text colour has an increased opacity on hover - it no longer has the background colour change
![Screenshot (6)_LI](https://user-images.githubusercontent.com/59174800/95843006-20d71780-0d3f-11eb-9706-7a297695c299.jpg)

**Comment by ebarry** [comment]
Thanks for everyone's work on this, this issue is fully resolved, and i'm going to close it. Thanks all!
