### ISSUE TITLE
/api/srch/notes/... API query is slowing down site with 1-2 minute long responses

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#5015]
Looks related to #3147 in some ways but for the title "related notes" suggestions shown at publiclab.org/post (to test, see https://stable.publiclab.org/post, our testing site, so as not to make the issue worse)

Or, https://stable.publiclab.org/api/srch/notes?query=coqui should trigger it directly on the stable test server. Interestingly, this isn't very slow, even though `stable.publiclab.org` is much lower power machine with the same sized database.

Skylight analysis:

https://oss.skylight.io/app/applications/GZDPChmcfm1Q/recent/6h/endpoints/Srch::Search%20%5BGET%5D%20srch%2Fnotes

Oddly, it seems not to be a SQL slowdown??? 

![image](https://user-images.githubusercontent.com/24359/54155554-c109e380-441a-11e9-8713-feaaef7b2af7.png)

Could this actually be slowing down due to something else?

**Comment by jywarren** [comment]
Yeah, see how it got worse and worse:

![image](https://user-images.githubusercontent.com/24359/54155810-4c837480-441b-11e9-90f5-b97a0d886f60.png)

I also see a few requests for profiles, so it's possible that was a root cause (since the users table is so giant) but not sure...

**Comment by jywarren** [comment]
It's just not very convincing that the notes api endpoint is the cause - it's a simple and limited query:

https://github.com/publiclab/plots2/blob/1eb99a97f1c0a78e3448cbb0995cedebc30b44d2/app/services/search_service.rb#L48-L51

I'm more inclined to think it could've been caused by another query and we're just seeing the effects but why would the loadtime affect this query and not other controllers?

**Comment by jywarren** [comment]
@icarito i think we need to do a deeper look at the long-running mysql queries?

**Comment by icarito** [comment]
Didn't find anything upon arriving
![imagen](https://user-images.githubusercontent.com/199755/54158074-b4d05700-4417-11e9-9eef-d51c34997477.png)

**Comment by icarito** [comment]
I'll run the requests_log_analyzer on the mysql_slow log like in the old days

**Comment by icarito** [comment]
I'm seeing a process related to the comment by tweet I think:
```
                                                                                                                                                              
 PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command                                                                                         
9562 root       20   0 1285M  333M 20644 R 69.2  4.2  0:27.37 ruby /usr/local/bin/bundle exec rails runner -e production Comment.receive_tweet                
9553 root       20   0  4288   748   676 S  0.0  0.0  0:00.00 sh -c /bin/bash -l -c 'cd /app && bundle exec rails runner -e production '\''Comment.receive_twe
9555 root       20   0  9520  2672  2432 S  0.0  0.0  0:00.00 bash -l -c cd /app && bundle exec rails runner -e production 'Comment.receive_tweet' >> /app/pub
9566 root       20   0 1285M  333M 20644 S  0.0  4.2  0:00.00 ruby bin/rails runner -e production Comment.receive_tweet                                       
9574 root       20   0 1285M  333M 20644 S  0.0  4.2  0:00.00 ruby bin/rails runner -e production Comment.receive_tweet                                       
9581 root       20   0 1285M  333M 20644 S  0.0  4.2  0:00.00 ruby bin/rails runner -e production Comment.receive_tweet                                       
```
Maybe this is the culprit?

**Comment by icarito** [comment]
![imagen](https://user-images.githubusercontent.com/199755/54159339-c2d3a700-441a-11e9-9736-88bfe8f52a86.png)
The regular shape suggests this could be a scheduled task?

**Comment by icarito** [comment]
Those processes `ruby /usr/local/bin/bundle exec rails runner -e production Comment.receive_tweet` take a big chunk of CPU

**Comment by icarito** [comment]
![imagen](https://user-images.githubusercontent.com/199755/54159634-6de46080-441b-11e9-8271-ea1e05454269.png)

**Comment by jywarren** [comment]
Great sleuthing! This is then connected to #4962 and specifically the Users query there.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/commit/a7ca3e9250e8b6b5a8317149f3658685462ac134 added -- any other way to break down what's taking so much CPU? I'll slow down the job too. 

Also set it to 10m intervals instead of 1 minute:

https://github.com/publiclab/plots2/commit/fa39d7a7e294f4352a4fe9daaaafaed2ff3e782f

**Comment by jywarren** [comment]
I merged those directly to master. will push to stable now for deployment, once we confirm https://stable.publiclab.org is working?

**Comment by icarito** [comment]
Yes sounds great. Every 10 minutes should be fine with the query optimization.

**Comment by icarito** [comment]
Hi, I'm glad we caught that one, but it does seem like the original issue is still with us.
![image](https://user-images.githubusercontent.com/199755/54328039-69b27180-45da-11e9-8d50-24c8f53db7d2.png)
Notice how it took longer and longer to respond. Could it be a limitation of the Full Text search engine?
I think @milaaraujo had a good lead here https://github.com/publiclab/plots2/issues/4661#issuecomment-455757923 that it might be the full text search engine?

**Comment by icarito** [comment]
![image](https://user-images.githubusercontent.com/199755/54645181-3e5fd480-4a69-11e9-8002-a119d78fa957.png)

This looks like way too many allocations?

**Comment by jywarren** [comment]
Here is the query backing it - looks simple, no? 

https://github.com/publiclab/plots2/blob/c59a6f07b45eacf1755a3e3583424a82d07253b3/app/services/search_service.rb#L48-L51

**Comment by jywarren** [comment]
It's a rich text search, though... so that leads down to:

https://github.com/publiclab/plots2/blob/c59a6f07b45eacf1755a3e3583424a82d07253b3/app/models/node.rb#L38-L54

It's all with `limit` though... 

You're saying it's allocating too many variables /per request/, not that there are too many requests?

**Comment by jywarren** [comment]
Actually it looks like there were close to 75 requests in just a 20m window - that could have been a single person: https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1553010420/22m/endpoints/Srch::Search%20%5BGET%5D%20srch%2Fnotes

**Comment by jywarren** [comment]
@icarito can you tell the exact query that's run 75 times here? The code splits out a few versions so I want to know which one we're looking to debug. They're pretty similar but it'd still be helpful i think.

**Comment by jywarren** [comment]
With the debounce working i find it hard to believe you could generate 75 requests from the "related work" feature in the editor, which hits this endpoint; doodling a bit on this line caused 5:

![Screen Shot 2019-03-19 at 6 44 26 PM](https://user-images.githubusercontent.com/24359/54646929-0bbcd880-4a77-11e9-9cd0-91570c0a4ca8.png)

Hmm, on the other hand, i kept typing and typing, and it definitely started to stall on Staging:

![Screen Shot 2019-03-19 at 6 45 24 PM](https://user-images.githubusercontent.com/24359/54646977-36a72c80-4a77-11e9-8bbb-6aa68638565d.png)

**Comment by jywarren** [comment]
This would possibly cause the kind of "staircase" issue we saw above...

**Comment by jywarren** [comment]
Yep:

![Screen Shot 2019-03-19 at 6 47 01 PM](https://user-images.githubusercontent.com/24359/54647022-6c4c1580-4a77-11e9-8630-6c4bcc3dec43.png)

**Comment by jywarren** [comment]
Oh! Also, we did not add debounce to the questions form! Doing that now, that'll help a lot too. This could've been from a question...

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pull/5184

**Comment by jywarren** [comment]
Yes, https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1553010000/38m/endpoints/Srch::Search%20%5BGET%5D%20srch%2Fnotes - about 7 hours ago this was posted: https://publiclab.org/notes/nviollier/03-19-2019/how-can-i-demonstrate-the-bioremediation-of-fungi

**Comment by jywarren** [comment]
So, longer debounces are now added with 1000ms, and we can make them even longer if we want. Let's:

1. keep watching Skylight to ensure we are properly throttling requests (and consider making debounce 2-3 seconds?)
2. keep digging into this query and why it's not efficient in the first place

**Comment by icarito** [comment]
Okay so we had another instance of the typeahead but still these queries are taking a lot of time. I'll try to figure out what they are but I'm under the impression time is spent on Ruby rather than the database, just because on high load situations when observing the process list, normally Mysql isn't at the top.

**Comment by jywarren** [comment]
Much much improved from a half-day's worth of data:

Yesterday: Typical response 40s / Problem response 54s - https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1552995780/13h48m/endpoints?query=Srch%3A%3ASearch%20%5BGET%5D%20srch%2Fnotes

Today: Typical response 10s / Problem response 28s -  https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1553065200/13h48m/endpoints?query=Srch%3A%3ASearch%20%5BGET%5D%20srch%2Fnotes

**Comment by jywarren** [comment]
I'm wondering if typical is now 10s, that's actually the time it takes when it's not like "under a DOS attack" -- and the time before the db query that appears to make it slow is just time queued:

![image](https://user-images.githubusercontent.com/24359/54718599-3ff4cf80-4b31-11e9-9139-b2505a7a601c.png)

**Comment by jywarren** [comment]
Instead of Ruby time, could it be queueing time? just waiting?

**Comment by jywarren** [comment]
This is still not ideal: https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1557960900/23h15m/endpoints/Srch::Search%20%5BGET%5D%20srch%2Fnotes

**Comment by jywarren** [comment]
And still mysterious what is actually taking up this time! Almost all of it is memory allocations, and before the query even runs! (although after a VERY fast `rsessions` query runs... could it be that?)

**Comment by jywarren** [comment]
Noting that this API query now returns no results for common searches... though publiclab/PublicLab.Editor#470 seems to show it working for some queries?

https://publiclab.org/api/srch/notes?query=balloon-mapping returns this for me:

`{"items":"","srchParams":{"query":"balloon-mapping","seq":null,"tag":null,"nwlat":null,"nwlng":null,"selat":null,"selng":null}}`

**Comment by jywarren** [comment]
Noting this may not be a performance issue at this point, but "whether we're getting results" - https://oss.skylight.io/app/applications/GZDPChmcfm1Q/1592238000/12h37m/endpoints/Srch::Search%20%5BGET%5D%20srch%2Fnotes doesn't show too many long load times and mostly i'm just getting no items.
