### ISSUE TITLE
Fix typo and remove the "new contributor" tag from the sidebar on profile page

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#6151]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [app/views/users/profile.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/users/profile.html.erb) in the `plots2` repository and edit the line 234 as shown below. 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
- <li class="mt-3"><h5>@<%= @profile_user.name %> <%= @profile_user.new_contributor %> asked</h5></li>
+ <li class="mt-3"><h5>@<%= @profile_user.name %> has</h5></li> 
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by CleverFool77** [comment]
Hey @NitinBhasneia
You can look into this first timer issue.
Thanks !!!

**Comment by NitinBhasneia** [comment]
ok I will do it thnx @CleverFool77

**Comment by NitinBhasneia** [comment]
@CleverFool77 I pushed a commit is anything more I have to do after that because it is telling "Merging Blocked"

**Comment by gauravano** [comment]
Hi @gautamig54 @CleverFool77, are you sure, we want to remove the `new contributor` label?

**Comment by gautamig54** [comment]
Yes, we still have the new contributor label with the name under the
profile page. Here I am removing it from the above of # of content section.
It is in the design as well.

**Comment by gauravano** [comment]
Ok, I can see that on website, it's appearing just as a link. So, ideally, we want to show it as a label like -- https://github.com/publiclab/plots2/pull/2740#issuecomment-391578310

**Comment by NitinBhasneia** [comment]
Anything more to do here @CleverFool77 ??
