### ISSUE TITLE
Remove "scroll to top" arrow key

### ISSUE THREAD

**Issue by debck** [publiclab/plots2#6435]
Please Note:  **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

### Problem

We can find that the scroll-to-top arrow key also appears when we are at the top of the page.
[here](https://publiclab.org/) 

![Screenshot (21)_LI](https://user-images.githubusercontent.com/33368759/66577359-d9033a80-eb96-11e9-8368-45b65acd6aad.jpg)

hence, we should add some javascript scroll function so that it becomes visible only when the user starts to scroll the page

**Comment by auralshin** [comment]
Is This issue Still open

**Comment by auralshin** [comment]
I am interested, want to claim it

**Comment by SidharthBansal** [comment]
@auralshin go ahead!

**Comment by debck** [comment]
**Uploaded on GCI dashboard**

**Comment by SidharthBansal** [comment]
@debck don't you think this issue is solved?
Can you please close this issue and delete the gci task?
Thanks

**Comment by debck** [comment]
No, it isn't solved. I can still see it here: https://publiclab.org/ . Can you please confirm?

**Comment by SidharthBansal** [comment]
Oh he has made the PR in his fork repo. Got it. 
**Published the task on GCI dashboard**

**Comment by 91097** [comment]
I am also interested I want to claim. how can I claim it can anyone help me please.

**Comment by cesswairimu** [comment]
Hi @91097, this issue has already been solved. I am adding your name here #7683  and we will ping you when we get a first-timer-issue for you. Thanks
