### ISSUE TITLE
overflowing code inappropriately appearing below the tag input box

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#9987]
### Please describe the problem (or idea)

There is overflowing code inappropriately appearing on the user interface below the tag input box: 
<img width="273" alt="Screen Shot 2021-08-03 at 3 33 30 PM" src="https://user-images.githubusercontent.com/161439/128075762-a579dbde-909a-47fc-97b6-fd34119c46a9.png">

`,{},False" data-provide="typeahead" />`

> What did you expect to see that you didn't?
i expected just to see the instructions "enter tags" and nothing else. 

# where is this happening? 

This is happening on both wiki pages and notes.

**Comment by anirudhprabhakaran3** [comment]
Hey, I'm not able to see this on the website from my end. Could you link maybe an URL or something that points to the page on which the error is showing up? That'll help me debug the issue more

**Comment by Manasa2850** [comment]
This has been fixed via #9973 I guess!

**Comment by noi5e** [comment]
I'm not able to reproduce this either. From `/profile/admin` on my local `main` branch:

<img width="281" alt="Screen Shot 2021-08-07 at 5 31 47 PM" src="https://user-images.githubusercontent.com/4361605/128617025-cc76e645-ad58-46e4-8a19-3282a4f9cdcf.png">

@ebarry Can you confirm if you're still seeing this, and where? The current site, or stable maybe?

**Comment by ebarry** [comment]
Hi! 
I re-checked just now, and I AM STILL seeing this on the live production site in the following locations: 

- on questions: https://publiclab.org/questions/fongvania/07-29-2021/how-can-community-science-projects-go-about-seeking-funding
- on notes: https://publiclab.org/notes/bhamster/08-06-2021/building-a-coqui-water-conductivity-sensor-and-analyzing-its-sound
- on wikis: https://publiclab.org/wiki/soil-sampling
- on profiles: https://publiclab.org/profile/liz

I am browsing in Chrome, logged in with an Admin privilege account "liz"

**Comment by anirudhprabhakaran3** [comment]
Aah i see it now too. Looking into the issue

**Comment by anirudhprabhakaran3** [comment]
I believe it is due to this part of code:
https://github.com/publiclab/plots2/blob/aeb6c35f16c1944f1f524becae3c710ed4282822/app/views/tag/_form.html.erb#L12

On line 12, the placeholder uses the translate() function. Everything after that is what is actually overflowing from the input form. Will have to dig into the translate() function.

I think that the function is returning a span which contains <code>"</code> or something similar that is tripping the HTML output.

**Comment by noi5e** [comment]
Maybe @imajit knows something about this, since it seems similar to stuff that they were working on?

**Comment by imajit** [comment]
I guess I had fixed this recently. Looking into it :worried:

**Comment by noi5e** [comment]
@imajit The solution might not yet have been pushed to the production server! @jywarren @icarito

**Comment by imajit** [comment]
Yeah, I guess that's the case here 
Sorry @ebarry for the trouble this was caused due to an FTO issue and the pr got pushed to production too.  This issue is only visible to Translation team members so won't be a site-wide issue.

**Comment by ebarry** [comment]
oh interesting! Ok, so am i understanding correctly that it's only currently visible to Translation Team members, and it will be fixed for them also once the site is republished?

**Comment by imajit** [comment]
Yes

**Comment by noi5e** [comment]
Still seeing this error in production at [this page](https://publiclab.org/questions/fongvania/07-29-2021/how-can-community-science-projects-go-about-seeking-funding) @ebarry mentioned. 

The PR I was thinking about is this one: #9856. Not sure if it truly is related or not 🤔 

I wonder if @imajit's fix for this has been pushed to production yet. I don't think it has.

**Comment by imajit** [comment]
It's not related to #9856 because that test would fail if the translation function or its dependencies fail to render UI correctly, but in this issue, the translation function did not fail the parameters passed were incorrect.

**Comment by jywarren** [comment]
Going through these pages now, and some seem resolved in production:

* [x] https://publiclab.org/questions/fongvania/07-29-2021/how-can-community-science-projects-go-about-seeking-funding
* [x] https://publiclab.org/notes/bhamster/08-06-2021/building-a-coqui-water-conductivity-sensor-and-analyzing-its-sound
* [x] on wikis: https://publiclab.org/wiki/soil-sampling
* [x] on profiles: https://publiclab.org/profile/liz

So this looks all good now, closing! Thank you all!

![image](https://user-images.githubusercontent.com/24359/131545736-c43d8885-6998-470b-9bcb-238c53d7bcb1.png)


![image](https://user-images.githubusercontent.com/24359/131545698-6ef55d6f-aec7-4d4a-af9c-a664201d21ed.png)

**Comment by jywarren** [comment]
I do see one overflow issue here but it's unrelated. Opening a separate issue! 

![image](https://user-images.githubusercontent.com/24359/131545386-12878abc-c301-445a-8810-5decdd95831d.png)
